version: 2.1
orbs:
  node: circleci/node@4.2.0
  terraform: circleci/terraform@dev:alpha
  # terraform: circleci/terraform@1.3.1
  docker: circleci/docker@1.5.0
jobs:
  run-tests:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
          cache-path: ~/project/node_modules
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results          
  build_docker_image:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>
      - docker/push:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 0.1.<< pipeline.number >>
  deploy_aws_ecs:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - terraform/install:
          terraform_version: "0.14.2"
          arch: "arm64"
          os: "linux"
      - terraform/init:
          path: ./terraform/aws/ecs
          backend: true
          backend_config_file: ./terraform/aws/ecs/remote.hcl
      - terraform/plan:
          path: ./terraform/aws/ecs
          # local_state: false
          backend_config_file: ./terraform/aws/ecs/remote.hcl
      - terraform/apply:
          path: ./terraform/aws/ecs
          # local_state: false
          backend_config_file: ./terraform/aws/ecs/remote.hcl
          var: "docker_img_name=${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME},docker_img_tag=0.1.<< pipeline.number >>"
  destroy_aws_ecs:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Create .terraformrc file locally
          command: echo "credentials \"app.terraform.io\" {token = \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
      - terraform/install:
          terraform_version: "0.14.2"
          arch: "arm64"
          os: "linux"
      - terraform/init:
          path: ./terraform/aws/ecs
          backend_config_file: ./terraform/aws/ecs/remote.hcl
      - terraform/plan:
          path: ./terraform/aws/ecs
          # local_state: false
          backend_config_file: ./terraform/aws/ecs/remote.hcl
      - terraform/destroy:
          path: ./terraform/aws/ecs
          # local_state: false
workflows:
  build:
    jobs:
      - run-tests
      - build_docker_image
      - deploy_aws_ecs
      - approve_destroy:
          type: approval
          requires:
            - deploy_aws_ecs
      - destroy_aws_ecs:
          requires:
            - approve_destroy